In [ ]:
## https://lsjsj92.tistory.com/570?category=853217

In [1]:
import pandas as pd
import numpy as np

In [2]:
movie = pd.read_csv('./mv_small/movies.csv')
rating = pd.read_csv('./mv_small/ratings.csv')
df = pd.merge(rating, movie, on='movieId')

In [3]:
# user - movie  //  movie - user 로 변경
u_m = pd.pivot_table(df, index='userId', values='rating', columns='title')
m_u = pd.pivot_table(df, index='title', values='rating', columns='userId')
# rating이 일정 수 이하인 movie는 drop
rtd = u_m.columns.values[u_m.count() < 20]
u_m = u_m.drop(rtd, axis=1).fillna(0)
m_u = m_u.drop(rtd).fillna(0)

In [4]:
u_m

title,(500) Days of Summer (2009),10 Things I Hate About You (1999),101 Dalmatians (1996),101 Dalmatians (One Hundred and One Dalmatians) (1961),12 Angry Men (1957),13 Going on 30 (2004),"13th Warrior, The (1999)",1408 (2007),2001: A Space Odyssey (1968),2012 (2009),...,Young Frankenstein (1974),Young Guns (1988),Zack and Miri Make a Porno (2008),Zodiac (2007),Zombieland (2009),Zoolander (2001),Zootopia (2016),eXistenZ (1999),xXx (2002),¡Three Amigos! (1986)
userId,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,...,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,...,3.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
607,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
608,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,3.0,0.0,4.5,3.5,0.0
609,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
610,3.5,0.0,0.0,0.0,0.0,0.0,0.0,4.0,4.5,3.0,...,0.0,0.0,3.5,5.0,3.5,4.0,4.0,0.0,2.0,0.0

In [5]:
m_u

userId,1,2,3,4,5,6,7,8,9,10,...,601,602,603,604,605,606,607,608,609,610
title,,,,,,,,,,,,,,,,,,,,,
(500) Days of Summer (2009),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.5
10 Things I Hate About You (1999),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,3.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0
101 Dalmatians (1996),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,4.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0
101 Dalmatians (One Hundred and One Dalmatians) (1961),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12 Angry Men (1957),0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zoolander (2001),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,4.0
Zootopia (2016),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
eXistenZ (1999),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,5.0,0.0,0.0,0.0,0.0,4.5,0.0,0.0
xXx (2002),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.5,0.0,2.0
¡Three Amigos! (1986),4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## Item based CF

In [6]:
from sklearn.metrics.pairwise import cosine_similarity

# 유사도 행렬
sim_df = pd.DataFrame(cosine_similarity(m_u), columns=m_u.index, index=m_u.index)
sim_df.head()

title,(500) Days of Summer (2009),10 Things I Hate About You (1999),101 Dalmatians (1996),101 Dalmatians (One Hundred and One Dalmatians) (1961),12 Angry Men (1957),13 Going on 30 (2004),"13th Warrior, The (1999)",1408 (2007),2001: A Space Odyssey (1968),2012 (2009),...,Young Frankenstein (1974),Young Guns (1988),Zack and Miri Make a Porno (2008),Zodiac (2007),Zombieland (2009),Zoolander (2001),Zootopia (2016),eXistenZ (1999),xXx (2002),¡Three Amigos! (1986)
title,,,,,,,,,,,,,,,,,,,,,
(500) Days of Summer (2009),1.000000,0.326122,0.206167,0.198959,0.222581,0.328675,0.118476,0.263401,0.203097,0.304648,...,0.143249,0.118215,0.401963,0.450463,0.402251,0.306076,0.260308,0.097935,0.276512,0.169385
10 Things I Hate About You (1999),0.326122,1.000000,0.282549,0.270490,0.095586,0.354539,0.258683,0.119866,0.191393,0.109431,...,0.224106,0.198068,0.280660,0.154749,0.227712,0.340590,0.110769,0.167085,0.176720,0.160426
101 Dalmatians (1996),0.206167,0.282549,1.000000,0.335155,0.189524,0.227161,0.056147,0.202090,0.206091,0.131299,...,0.248891,0.082955,0.157085,0.127568,0.181224,0.246544,0.110579,0.094899,0.198621,0.127186
101 Dalmatians (One Hundred and One Dalmatians) (1961),0.198959,0.270490,0.335155,1.000000,0.201484,0.255016,0.179939,0.265322,0.196903,0.151696,...,0.250532,0.185809,0.161520,0.142079,0.234138,0.328696,0.131859,0.130010,0.285099,0.213821
12 Angry Men (1957),0.222581,0.095586,0.189524,0.201484,1.000000,0.028113,0.137482,0.234352,0.291756,0.272876,...,0.220096,0.187897,0.151745,0.295817,0.217742,0.196745,0.119460,0.053689,0.125459,0.154989

In [7]:
def get_item_based_cf(movieId, top_n=20):
    return sim_df[movieId].sort_values(ascending=False).iloc[1:top_n+1]
get_item_based_cf('Zootopia (2016)')

title
Inside Out (2015)                                    0.601073
Deadpool (2016)                                      0.581750
Big Hero 6 (2014)                                    0.574437
Star Wars: Episode VII - The Force Awakens (2015)    0.565219
Guardians of the Galaxy (2014)                       0.564004
Mad Max: Fury Road (2015)                            0.536005
Doctor Strange (2016)                                0.534756
Kingsman: The Secret Service (2015)                  0.514448
The Lego Movie (2014)                                0.510291
How to Train Your Dragon (2010)                      0.503934
Ant-Man (2015)                                       0.474897
Guardians of the Galaxy 2 (2017)                     0.472706
Avengers, The (2012)                                 0.470278
Brave (2012)                                         0.470274
Logan (2017)                                         0.469623
Captain America: The Winter Soldier (2014)           0.464178
Avatar (2009)                                        0.458680
Despicable Me (2010)                                 0.444178
Rogue One: A Star Wars Story (2016)                  0.443488
Avengers: Age of Ultron (2015)                       0.438017
Name: Zootopia (2016), dtype: float64

## latent factor CF

In [8]:
from sklearn.decomposition import TruncatedSVD

SVD = TruncatedSVD(n_components=12)
mat = SVD.fit_transform(m_u)

In [9]:
mat.shape

(1297, 12)

In [10]:
corr = np.corrcoef(mat)
corr

array([[1.        , 0.71005798, 0.60052206, ..., 0.28179517, 0.63604302,
        0.40765711],
       [0.71005798, 1.        , 0.65485188, ..., 0.55100147, 0.49645702,
        0.56268583],
       [0.60052206, 0.65485188, 1.        , ..., 0.23097654, 0.53862534,
        0.45368196],
       ...,
       [0.28179517, 0.55100147, 0.23097654, ..., 1.        , 0.54815602,
        0.49819084],
       [0.63604302, 0.49645702, 0.53862534, ..., 0.54815602, 1.        ,
        0.31254368],
       [0.40765711, 0.56268583, 0.45368196, ..., 0.49819084, 0.31254368,
        1.        ]])

In [11]:
def get_lf_cf(title, top_n=20):
    titles = list(m_u.index)
    idx = list(m_u.index).index(title)
    cor = corr[idx]
    return np.array(titles)[np.argsort(-cor)[1:top_n+1]]

In [12]:
for t in get_lf_cf('Zootopia (2016)'):
    print(t)

Sherlock Holmes: A Game of Shadows (2011)
Despicable Me (2010)
Avengers, The (2012)
Big Hero 6 (2014)
Pirates of the Caribbean: On Stranger Tides (2011)
Guardians of the Galaxy (2014)
Inside Out (2015)
Guardians of the Galaxy 2 (2017)
Edge of Tomorrow (2014)
Mad Max: Fury Road (2015)
Captain America: The First Avenger (2011)
Deadpool (2016)
X-Men: First Class (2011)
Kingsman: The Secret Service (2015)
Captain America: The Winter Soldier (2014)
Thor: The Dark World (2013)
The Hunger Games: Mockingjay - Part 1 (2014)
Thor (2011)
Adjustment Bureau, The (2011)
The Lego Movie (2014)

## factorization CF

In [13]:
def non_zero_mean(x):
    return np.sum(x, axis=1) / np.count_nonzero(x, axis=1)

In [14]:
v = u_m.values
diff_v = np.where(v==0, 0, v-non_zero_mean(v).reshape(-1, 1))
u_m_ = pd.DataFrame(diff_v, columns=u_m.columns, index=u_m.index)
u_m_

title,(500) Days of Summer (2009),10 Things I Hate About You (1999),101 Dalmatians (1996),101 Dalmatians (One Hundred and One Dalmatians) (1961),12 Angry Men (1957),13 Going on 30 (2004),"13th Warrior, The (1999)",1408 (2007),2001: A Space Odyssey (1968),2012 (2009),...,Young Frankenstein (1974),Young Guns (1988),Zack and Miri Make a Porno (2008),Zodiac (2007),Zombieland (2009),Zoolander (2001),Zootopia (2016),eXistenZ (1999),xXx (2002),¡Three Amigos! (1986)
userId,,,,,,,,,,,,,,,,,,,,,
1,0.000000,0.0,0.0,0.0,0.000000,0.0,-0.40884,0.000000,0.000000,0.000000,...,0.591160,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,-0.40884
2,0.000000,0.0,0.0,0.0,0.000000,0.0,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.000000,-0.934783,0.000000,0.000000,0.00000,0.000000,0.00000
3,0.000000,0.0,0.0,0.0,0.000000,0.0,0.00000,0.000000,0.000000,-1.068182,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000
4,0.000000,0.0,0.0,0.0,1.434783,0.0,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000
5,0.000000,0.0,0.0,0.0,0.000000,0.0,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,0.000000,0.0,0.0,0.0,0.000000,0.0,0.00000,0.000000,1.332976,0.000000,...,-0.167024,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000
607,0.000000,0.0,0.0,0.0,0.000000,0.0,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000
608,0.000000,0.0,0.0,0.0,0.000000,0.0,0.00000,0.000000,-0.260540,0.000000,...,0.000000,0.0,0.000000,0.000000,0.000000,-0.260540,0.000000,1.23946,0.239460,0.00000
609,0.000000,0.0,0.0,0.0,0.000000,0.0,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000
610,-0.445591,0.0,0.0,0.0,0.000000,0.0,0.00000,0.054409,0.554409,-0.945591,...,0.000000,0.0,-0.445591,1.054409,-0.445591,0.054409,0.054409,0.00000,-1.945591,0.00000

In [15]:
from scipy.sparse.linalg import svds

In [16]:
u,sigma, vt = svds(u_m_, k=12)
sigma = np.diag(sigma)

In [17]:
u.shape, sigma.shape, vt.shape

((610, 12), (12, 12), (12, 1297))

In [18]:
# 점수를 복원했고 해당 유저에게 맞춤형 추천을 할 수 있어진다.
pred_ratings =  np.dot(np.dot(u, sigma), vt)+non_zero_mean(v).reshape(-1, 1)
pred_ratings = pd.DataFrame(pred_ratings, index=u_m.index, columns=u_m.columns)
pred_ratings

title,(500) Days of Summer (2009),10 Things I Hate About You (1999),101 Dalmatians (1996),101 Dalmatians (One Hundred and One Dalmatians) (1961),12 Angry Men (1957),13 Going on 30 (2004),"13th Warrior, The (1999)",1408 (2007),2001: A Space Odyssey (1968),2012 (2009),...,Young Frankenstein (1974),Young Guns (1988),Zack and Miri Make a Porno (2008),Zodiac (2007),Zombieland (2009),Zoolander (2001),Zootopia (2016),eXistenZ (1999),xXx (2002),¡Three Amigos! (1986)
userId,,,,,,,,,,,,,,,,,,,,,
1,4.381725,4.309625,4.355750,4.391183,4.461816,4.386051,4.352568,4.355676,4.598213,4.359397,...,4.459967,4.454740,4.456003,4.382900,4.475214,4.538337,4.359473,4.354540,4.376659,4.382589
2,3.932734,3.943218,3.936022,3.929995,3.926978,3.933430,3.934747,3.927001,3.929613,3.934675,...,3.947212,3.920509,3.937413,3.936221,3.934416,3.948474,3.935411,3.931478,3.926063,3.938254
3,1.541872,1.540718,1.601136,1.542048,1.523465,1.547513,1.599780,1.566430,1.549071,1.567259,...,1.629394,1.546326,1.556696,1.571962,1.529644,1.592913,1.589286,1.585862,1.553941,1.549175
4,3.430364,3.611728,3.479059,3.621372,3.842816,3.585018,3.463500,3.488655,3.767663,3.529758,...,3.824163,3.477746,3.630440,3.567254,3.676855,3.595061,3.474794,3.443953,3.475473,3.628144
5,3.598234,3.568432,3.602486,3.620750,3.673768,3.619366,3.612963,3.626704,3.658976,3.626653,...,3.623159,3.638527,3.599491,3.609060,3.604840,3.576876,3.595545,3.605009,3.635249,3.601577
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,3.720036,3.617430,3.488456,3.680343,3.996477,3.693725,3.514958,3.635858,4.160228,3.594691,...,3.955074,3.366960,3.608300,3.738465,3.748665,3.583992,3.619416,3.786666,3.669004,3.582609
607,3.786156,3.764360,3.803496,3.800725,3.759415,3.756792,3.733658,3.794677,3.743050,3.735142,...,3.599888,3.629355,3.679027,3.735416,3.735966,3.571979,3.776838,3.822306,3.745680,3.699277
608,3.671285,2.581006,2.718952,2.911284,2.708420,2.999657,2.817444,3.372315,2.295206,3.255916,...,3.100934,3.264206,3.346118,3.068597,3.599228,3.520404,3.345370,3.950456,3.765150,2.900457
609,3.283682,3.247230,3.282613,3.283813,3.317012,3.276765,3.286974,3.285378,3.252328,3.280500,...,3.272246,3.280404,3.275784,3.277359,3.289929,3.270729,3.271953,3.285180,3.291188,3.285347
610,3.775018,4.051156,3.875421,3.822479,4.091233,3.820111,3.953582,3.808579,4.547194,3.513733,...,4.327385,3.624318,3.852144,4.075853,4.040438,4.058898,4.093024,3.844315,3.189258,3.877327

In [19]:
# import seaborn as sns

# sns.distplot(pred_ratings.iloc[6])